BigCommerce: Fix exception of missing key in order data
This will fix this exception:

```
KeyError: 'attributes'
  File "bigcommerce_core/views.py", line 751, in get_context_data
    self.normalize_orders(context)
  File "bigcommerce_core/views.py", line 995, in normalize_orders
    order_data['variant'] = self.get_order_data_variant(product, item)
  File "bigcommerce_core/views.py", line 843, in get_order_data_variant
    for attribute in data['attributes']:
```